name: CI

on:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install the Nix package manager
        uses: cachix/install-nix-action@V28
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"

      - uses: cachix/cachix-action@v15
        with:
          name: nixpkgs-azerothcore
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
  
      - name: Flake Check
        run: nix flake check
